[package]
name = "laraxum"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/coolCucumber-cat/laraxum.git"
readme = "../README.md"
description = """

"""
categories = ["database"]

[dependencies]
axum = "0.8.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["rt-multi-thread"] }
mime = "0.3.17"
bytes = "1.10.1"
chrono = { version = "0.4.41", optional = true }
time = { version = "0.3.41", optional = true }

[features]
default = ["mysql"]

macros = []

mysql = ["sqlx/mysql"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

chrono = ["dep:chrono"]
time = ["dep:time"]
