[package]
name = "laraxum_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.100"
quote = "1.0.39"
proc-macro2 = "1.0.94"
fmt2 = "0.3.4"

[features]
default = [
	# temp
	"dev_default",
]
dev_default = ["mysql"]

mysql = []
postgres = []
sqlite = []
