[package]
name = "laraxum_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full", "extra-traits"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
fmt2 = "0.3.4"
darling = "0.20.11"

[features]
default = [
	# temp
	"dev_default",
]
dev_default = ["mysql"]

mysql = []
postgres = []
sqlite = []

nightly = ["try_blocks"]
try_blocks = []
